### ISSUE TITLE
Passing an Error object in throws an error

### ISSUE THREAD

**Issue by doowb** [jonschlinkert/define-property#1]
When trying to define a property on an `Error` object:

```js
const err = new Error('something');
define(err, 'foo', 'bar');
```

 the following error is thrown:

```
TypeError: expected an object or function
```

This is happening since `kind-of` is returning `error` since it's an instance of an error. I know we can update this to include checking for a type of `error` object, but there are probably other types that are valid.

Should this just do a `typeof obj` check to get all the other types?

**Comment by jonschlinkert** [comment]
> Should this just do a typeof obj check to get all the other types?

I had `isobject` in here I think. we can use that
